# Generated by Django 5.2 on 2026-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='course',
            field=models.CharField(max_length=150, verbose_name='Intitulé du cours'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(verbose_name='Heure fin'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.CharField(max_length=50, verbose_name='Salle'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='Heure début'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.CharField(max_length=100, verbose_name='Professeur'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week_number',
            field=models.IntegerField(default=1, verbose_name='Numéro semaine'),
        ),
    ]
