# Generated by Django 6.0.5 on 2026-05-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='L3', max_length=255),
            preserve_default=False,
        ),
    ]
